name: skill_sharing_platform
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  video_player: ^2.4.10
  go_router: ^13.0.0
  flutter_riverpod: ^2.0.0
  hooks_riverpod: ^2.0.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - 'assets/images/'
    - 'assets/videos/'

